version: 0.2

phases:
    install:
        runtime-versions:
            dotnet: 6.0
    build:
        commands:
            - dotnet build -c Release ./Tailspin.SpaceGame.Web/Tailspin.SpaceGame.Web.csproj